### ISSUE TITLE
Fails to reconnect after connection restore attempt

### ISSUE THREAD

**Issue by Faek** [noobot/noobot#56]
I am running a noobot instance in command prompt (not installed as service) and it won't stay connected reliably. This is the error message I get (from websockets.log) and then it never reconnects:

```
12/13/2016 2:01:09 AM|Fatal|WebSocket.processException:0|WebSocketSharp.WebSocketException: The header part of a frame cannot be read from the data source.
                               at WebSocketSharp.WebSocketFrame.<>c__DisplayClass7.<ReadAsync>b__6(Byte[] header)
                               at WebSocketSharp.Ext.<>c__DisplayClass6.<ReadBytesAsync>b__5(IAsyncResult ar)

12/13/2016 2:01:31 AM|Fatal|WebSocket.processException:0|System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.172.82.211:443
                               at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
                               at WebSocketSharp.WebSocket.setClientStream()
                               at WebSocketSharp.WebSocket.doHandshake()
                               at WebSocketSharp.WebSocket.connect()
```

**Comment by Workshop2** [comment]
Thanks for reporting this - I am also getting a similar issue and have been investigating into it, I attempted to create a reconnect plugin but it needs improving.

What version of noobot are you using?

**Comment by Faek** [comment]
I'm using the latest version from nuget, 1.0.6157.16083

**Comment by Faek** [comment]
I'll try to get the call stack from the console window next time. It looks like something is messing up with the async/tasks when trying to reconnect in that call stack.

**Comment by Workshop2** [comment]
Thanks @faek

**Comment by Workshop2** [comment]
@faek does this still happen on the latest version?

**Comment by Faek** [comment]
I am happy to report the bot has stayed connected since running with the newest patch, for probably a week now.

**Comment by Workshop2** [comment]
Great news - thanks @Faek

**Comment by Workshop2** [comment]
Looks like it is still happening

```
2017-01-03 14:29:42.4042|INFO|Noobot.Service.NoobotHost|Stopping connection health plugin...
2017-01-03 14:29:42.4042|INFO|Noobot.Service.NoobotHost|Disconnected from server, attempting to reconnect...
2017-01-03 14:29:42.4042|INFO|Noobot.Service.NoobotHost|Reconnecting...
2017-01-03 14:30:01.2509|DEBUG|Quartz.Core.QuartzSchedulerThread|Batch acquisition of 0 triggers
2017-01-03 14:30:07.9945|INFO|Noobot.Service.NoobotHost|Error while reconnecting: System.AggregateException: One or more errors occurred. ---> SlackConnector.Exceptions.CommunicationException: Error occured while sending message '0'
   at SlackConnector.Connections.Clients.ResponseVerifier.VerifyResponse[T](IRestResponse response)
   at SlackConnector.Connections.Clients.RequestExecutor.<Execute>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SlackConnector.Connections.Clients.Handshake.HandshakeClient.<FirmShake>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SlackConnector.SlackConnector.<Connect>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Noobot.Core.NoobotCore.<Connect>d__6.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) SlackConnector.Exceptions.CommunicationException: Error occured while sending message '0'
   at SlackConnector.Connections.Clients.ResponseVerifier.VerifyResponse[T](IRestResponse response)
   at SlackConnector.Connections.Clients.RequestExecutor.<Execute>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SlackConnector.Connections.Clients.Handshake.HandshakeClient.<FirmShake>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SlackConnector.SlackConnector.<Connect>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Noobot.Core.NoobotCore.<Connect>d__6.MoveNext()<---
```

**Comment by Faek** [comment]
Yes, I am still getting this same exact error, but it's a lot more rare now. The day I reported it was working, it failed...haha

**Comment by freljung** [comment]
As far as I can see, If the Reconnect flow is entered, and reconnect fails during Connect, Noobot remains offline. I assume this is because when NoobotCore.OnDisconnect is called all plugins are stopped and are not started again until Connect is completed. Since Connect never completes, the ConnectionPlugin does not restart again.

I could come up with a fix if wanted. My initial thoughts on a solution would be to refactor the ConnectionPlugin functionality into a class that NoobotHost can use to start and stop the connection. That class can then handle reconnect and health scenarios.

**Comment by Workshop2** [comment]
Hi @freljung thanks for looking at this.

I have been updating SlackConnector to handle disconnects and reconnects. When I finish it I will then remove all of the reconnect stuff in Noobot.

Many thanks,
Simon

**Comment by freljung** [comment]
No worries. :) I like the structure of the code, and it's clear and easy to read, so I'm having a fun time when I go digging into it. If there's something specific that needs a bit of attention I can probably help.

**Comment by gplumb** [comment]
Hi all - was just curious if the SlackConnector ever got updated?

**Comment by Workshop2** [comment]
Hi @gplumb - it's still in progress. Life issues has meant I haven't been working on OSS but I plan to get back to it soon 👍

**Comment by gplumb** [comment]
@Workshop2 Sorry to hear that - If I can find time next week, I'll take a sneak-peak myself and PR :+1:
